/**
 * Centralised notification helper.
 * Before inserting a notification it checks the recipient's
 * notification_preferences and skips the insert if the relevant
 * toggle is off.
 *
 * NOTE: level_up and review_like notifications are generated by
 * Supabase DB-side functions (RPC / triggers) and are NOT covered here.
 * Preference enforcement for those types must be handled at the DB level.
 *
 * NOTE 2: actor_birthday and new_release are system notifications (no user actor).
 * For these types actor_id is omitted.
 */
import type { SupabaseClient } from '@supabase/supabase-js'

export type NotifType =
  | 'follow'
  | 'review_like'
  | 'review_comment'
  | 'comment_reply'
  | 'mention'
  | 'level_up'
  | 'list_like'
  | 'list_comment'
  | 'actor_birthday'
  | 'new_release'

const PREF_KEY: Record<NotifType, string> = {
  follow:         'follows',
  review_like:    'likes',
  review_comment: 'comments',
  comment_reply:  'replies',
  mention:        'mentions',
  level_up:       'level_up',
  list_like:      'list_like',
  list_comment:   'list_comment',
  actor_birthday: 'actor_birthday',
  new_release:    'new_release',
}

export interface NotifPayload {
  user_id:       string
  actor_id?:     string       // omitted for system notifications (birthday, new_release)
  type:          NotifType
  review_id?:    string
  review_title?: string
  read?:         boolean
  comment_id?:   string
  actor_username?: string
  actor_avatar?:   string
  entity_id?:    string       // list id / actor id / movie id
  entity_type?:  string       // 'list' | 'person' | 'movie'
  entity_title?: string       // list name / actor name / movie title
}

export async function sendNotification(
  supabase: SupabaseClient,
  payload: NotifPayload
): Promise<void> {
  const prefKey = PREF_KEY[payload.type]

  // Check recipient's preference
  const { data } = await supabase
    .from('profiles')
    .select('notification_preferences')
    .eq('id', payload.user_id)
    .maybeSingle()

  if (data) {
    const prefs = (data as { notification_preferences: Record<string, boolean> | null })
      .notification_preferences ?? {}
    if (prefs[prefKey] === false) return
  }

  const { error } = await supabase.from('notifications').insert(payload)
  if (error) { console.error(`[notify] ${payload.type}:`, error.message); return }

  // Fire-and-forget push — only from browser context (web-push is server-only)
  if (typeof window !== 'undefined') {
    fetch('/api/send-push', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        userId:      payload.user_id,
        type:        payload.type,
        actorName:   payload.actor_username,
        entityTitle: payload.entity_title ?? payload.review_title,
        entityId:    payload.entity_id,
      }),
    })
      .then(res => {
        if (!res.ok) {
          res.json().catch(() => null).then(b =>
            console.warn('[push] send-push failed', res.status, b)
          )
        }
      })
      .catch(err => console.warn('[push] fetch error:', err))
  }
}
