/**
 * Centralised notification helper.
 * Before inserting a notification it checks the recipient's
 * notification_preferences and skips the insert if the relevant
 * toggle is off.
 *
 * NOTE: level_up and review_like notifications are generated by
 * Supabase DB-side functions (RPC / triggers) and are NOT covered here.
 * Preference enforcement for those types must be handled at the DB level.
 */
import type { SupabaseClient } from '@supabase/supabase-js'

type NotifType =
  | 'follow'
  | 'review_like'
  | 'review_comment'
  | 'comment_reply'
  | 'mention'
  | 'level_up'

const PREF_KEY: Record<NotifType, string> = {
  follow:         'follows',
  review_like:    'likes',
  review_comment: 'comments',
  comment_reply:  'replies',
  mention:        'mentions',
  level_up:       'level_up',
}

export interface NotifPayload {
  user_id: string
  actor_id: string
  type: NotifType
  review_id?: string
  review_title?: string
  read?: boolean
  comment_id?: string
  actor_username?: string
  actor_avatar?: string
}

export async function sendNotification(
  supabase: SupabaseClient,
  payload: NotifPayload
): Promise<void> {
  const prefKey = PREF_KEY[payload.type]

  // Check recipient's preference
  const { data } = await (supabase as SupabaseClient)
    .from('profiles')
    .select('notification_preferences')
    .eq('id', payload.user_id)
    .maybeSingle()

  if (data) {
    const prefs = (data as { notification_preferences: Record<string, boolean> | null })
      .notification_preferences ?? {}
    if (prefs[prefKey] === false) return
  }

  const { error } = await supabase.from('notifications').insert(payload)
  if (error) console.error(`[notify] ${payload.type}:`, error.message)
}
